
puts "/::::----------------------................----------------------::::/"
puts "::--------------......................................--------------::"
puts ":------------.............................................-----------:"
puts ":------.............................oho-......................--------"
puts "----..............................-ydmmd+.........................----"
puts "-oso/-...................```````-sdhhhyhhh-`.........................-"
puts "-:mNmmds:....`````..````..--::/+oydhhddhhddhho+ooos+/+/-.............."
puts "../ys+:-:/::--.../+s++++osoooysysysyhhhmddmdhhhhhddmmNNNNmhyo/-......."
puts ".``/mNmmmyhs+/+oooo+:/---:-://shydhhddddmmmmmmmmNNmNNNNNNMMMNNmNmds:.."
puts ".```oNNNhydddyysss+/:+osydhhsymmNNNNNNmmNNNNNNNMNNMMNNmmmmNNMMMMMMMMs."
puts ".``smdhohddsyyhyyhyyyys+oo+shdhhhssyhhhhhyyyymdyddmmddddddmdmmmmmmNN+`"
puts "``hNNmmmso:.`    -+ossooyyyhymdhdNMMMMMNdhmmmhhmmmmmmdddmmNNNNNmho/.``"
puts ".sdNds/-`         -ossys/.-::--://+ohsydydddhhhddmdmdddhooo+:-`      `"
puts ".-..               .ys/-          .syys+`.-:/:.``:/:..`              `"
puts "`                   .:            :mhms`                             `"
puts "`                                  .``                               `"
puts "`                                                                    `"
puts "`                                                                    `"
puts "````                                                              ````"